version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  # app:
  #   build: .
  #   restart: always
  #   environment:
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
    